spring:
  application:
    name: firstspringbootbyrahul

  datasource:
    url: jdbc:postgresql://db.brsdiyptapiuiflnuiat.supabase.co:5432/postgres?sslmode=require
    username: postgres
    password: AdiRa@1304@
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 30000
      max-lifetime: 600000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

# server:
#   port: 9090